// DO NOT MODIFY. This file is autogenerated by the FirebaseCLI.
'use client';

import {useState, useEffect} from 'react';
import {doc, onSnapshot, DocumentReference, DocumentData} from 'firebase/firestore';
import {useFirestore} from '@/firebase/provider';

interface IDocument<T> {
  loading: boolean;
  data: T & {id: string} | null;
  error: Error | null;
}

export function useDoc<T = DocumentData>(
  docRef: DocumentReference | null
): IDocument<T> {
  const [data, setData] = useState<(T & {id: string}) | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    if (!docRef) {
      setLoading(false);
      return;
    }

    const unsubscribe = onSnapshot(
      docRef,
      (snapshot) => {
        if (snapshot.exists()) {
          const data = {
            id: snapshot.id,
            ...snapshot.data(),
          } as T & {id: string};
          setData(data);
        } else {
          setData(null);
        }
        setLoading(false);
      },
      (err) => {
        setError(err);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [docRef]);

  return {loading, data, error};
}
