// DO NOT MODIFY. This file is autogenerated by the FirebaseCLI.
'use client';

import {useState, useEffect} from 'react';
import {
  collection,
  query,
  onSnapshot,
  Query,
  DocumentData,
} from 'firebase/firestore';
import {useFirestore} from '@/firebase/provider';

interface ICollection<T> {
  loading: boolean;
  data: (T & {id: string})[] | null;
  error: Error | null;
}

export function useCollection<T = DocumentData>(
  collectionQuery: Query | null
): ICollection<T> {
  const [data, setData] = useState<(T & {id: string})[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    if (!collectionQuery) {
      setLoading(false);
      return;
    }

    const unsubscribe = onSnapshot(
      collectionQuery,
      (snapshot) => {
        const data: (T & {id: string})[] = snapshot.docs.map(
          (doc) =>
            ({
              id: doc.id,
              ...doc.data(),
            } as T & {id: string})
        );
        setData(data);
        setLoading(false);
      },
      (err) => {
        setError(err);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [collectionQuery]);

  return {loading, data, error};
}
