// DO NOT MODIFY. This file is autogenerated by the FirebaseCLI.
import {FirebaseOptions} from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  "apiKey": "API_KEY",
  "authDomain": "AUTH_DOMAIN",
  "projectId": "PROJECT_ID",
  "storageBucket": "STORAGE_BUCKET",
  "messagingSenderId": "MESSAGING_SENDER_ID",
  "appId": "APP_ID",
  "measurementId": "MEASUREMENT_ID"
};
