// DO NOT MODIFY. This file is autogenerated by the FirebaseCLI.
import {FirebaseOptions} from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  "projectId": "studio-8870656943-56ecc",
  "appId": "1:105272091924:web:a8c6a59ec326f8cb10ce01",
  "apiKey": "AIzaSyCEEI9Eq_RD8-cLKv4Ag_vT3rcZJWi9b_o",
  "authDomain": "studio-8870656943-56ecc.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "105272091924",
  "storageBucket": "studio-8870656943-56ecc.appspot.com"
};
