// DO NOT MODIFY. This file is autogenerated by the FirebaseCLI.
'use client';
import {initializeApp, getApp, getApps, FirebaseApp} from 'firebase/app';
import {getFirestore, Firestore} from 'firebase/firestore';
import {getAuth, Auth} from 'firebase/auth';
import {firebaseConfig} from './config';
import {
  FirebaseProvider,
  useFirebase,
  useFirebaseApp,
  useFirestore,
  useAuth,
} from './provider';
import {FirebaseClientProvider} from './client-provider';
import {useCollection} from './firestore/use-collection';
import {useDoc} from './firestore/use-doc';
import {useUser} from './auth/use-user';
import {FirestorePermissionError} from './errors';

let firebaseApp: FirebaseApp;
if (!getApps().length) {
  firebaseApp = initializeApp(firebaseConfig);
} else {
  firebaseApp = getApp();
}

const auth = getAuth(firebaseApp);
const firestore = getFirestore(firebaseApp);

export function initializeFirebase() {
  return {
    firebaseApp,
    firestore,
    auth,
  };
}

export {
  FirebaseProvider,
  FirebaseClientProvider,
  useCollection,
  useDoc,
  useUser,
  useFirebase,
  useFirebaseApp,
  useFirestore,
  useAuth,
  FirestorePermissionError,
};
